POST http://localhost:3010/api/v1/auth/register HTTP/1.1
Content-Type: application/json

{
    "name" : "ValentinAdmin",
    "lastname": "RigoniAdmin",
    "email" : "admin@gmail.com",
    "whatsapp": "3585009887",
    "age": 25,
    "password": "admingranted",
    "permissions": ["admin_granted"],
    "roles" : ["688d33cb2e2f933d27627d04"]
}

###
POST http://localhost:3010/api/v1/auth/register HTTP/1.1
Content-Type: application/json

{
    "name" : "ValentinUser",
    "lastname": "RigoniUser",
    "email" : "user@gmail.com",
    "whatsapp": "3585009882",
    "age": 25,
    "password": "usergranted",
    "roles" : ["688d35f55f0da19dfa9f2b97"]
}


###
POST http://localhost:3010/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password" : "admingranted"
}

###d
GET http://localhost:3010/api/v1/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YmRlMWE4NWU5MDQ0NzFhYzI5ZDdlNyIsImVtYWlsIjoiZ3Vlc3RAZ21haWwuY29tIiwidXNlcm5hbWUiOiJ1c3VhcmlvR3Vlc3QiLCJyb2xlcyI6W3siX2lkIjoiNjdiZGQ3ZmZlNmRjYWNmYmVmZTZjOThhIiwibmFtZSI6Imd1ZXN0IiwicGVybWlzc2lvbnMiOltdLCJjcmVhdGVkQXQiOiIyMDI1LTAyLTI1VDE0OjQ3OjI3LjU4NFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTAyLTI1VDE0OjQ3OjI3LjU4NFoifV0sIm5hdGlvbmFsaXR5IjoiQXJnZW50aW5hIiwibG9jYWxpdHkiOiJDb3Jkb2JhIiwiYWdlIjoyNSwiaWF0IjoxNzQwNjY4OTIyLCJleHAiOjE3NDA2NzYxMjJ9.QLNHKcuXytoUwarsUhJcjYaJ-1QPSd58YRbh6BzXd84