### Crear pregunta
POST http://localhost:4000/api/v1/questions HTTP/1.1
Content-Type: application/json
Authorization: Bearer <TU_TOKEN_DE_ADMIN>

{
  "text": "¿Pregunta de prueba?",
  "category": "biologia"
}

### Listar preguntas
GET http://localhost:4000/api/v1/questions HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjU1NDRmN2Y5M2VkNWEzYjJiY2MzYyIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwidXNlcm5hbWUiOiJ1c3VhcmlvQWRtaW4iLCJyb2xlcyI6W3siX2lkIjoiNjdiMWY3ZjMwNGZiYTUzODZiNDY4NmE2IiwibmFtZSI6ImFkbWluIiwicGVybWlzc2lvbnMiOlsiYWRtaW5fZ3JhbnRlZCJdLCJjcmVhdGVkQXQiOiIyMDI1LTAyLTE2VDE0OjM2OjM1LjMyMVoiLCJ1cGRhdGVkQXQiOiIyMDI1LTAyLTE2VDE0OjM2OjM1LjMyMVoifV0sImlhdCI6MTc0MDE3NDQ2NCwiZXhwIjoxNzQwMTgxNjY0fQ.FPEwkjDPbQARSJZqyjDaw3a-S_loZQ34-O8RNwB3u5s


### Listar preguntas por id
GET http://localhost:4000/api/v1/questions/{id} HTTP/1.1
Authorization: Bearer <TU_TOKEN_DE_ADMIN>

### Listar preguntas por usuario
GET http://localhost:4000/api/v1/questions?user=67b5547f7f93ed5a3b2bcc40&category=biologia HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjU1NDRmN2Y5M2VkNWEzYjJiY2MzYyIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwidXNlcm5hbWUiOiJ1c3VhcmlvQWRtaW4iLCJyb2xlcyI6W3siX2lkIjoiNjdiMWY3ZjMwNGZiYTUzODZiNDY4NmE2IiwibmFtZSI6ImFkbWluIiwicGVybWlzc2lvbnMiOlsiYWRtaW5fZ3JhbnRlZCJdLCJjcmVhdGVkQXQiOiIyMDI1LTAyLTE2VDE0OjM2OjM1LjMyMVoiLCJ1cGRhdGVkQXQiOiIyMDI1LTAyLTE2VDE0OjM2OjM1LjMyMVoifV0sImlhdCI6MTc0MDE3NDQ2NCwiZXhwIjoxNzQwMTgxNjY0fQ.FPEwkjDPbQARSJZqyjDaw3a-S_loZQ34-O8RNwB3u5s

### Listar preguntas por categoria y estado pendiente
GET http://localhost:4000/api/v1/questions?category=biologia&status=pending HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjU1NDdmN2Y5M2VkNWEzYjJiY2M0MCIsImVtYWlsIjoidXNlckBnbWFpbC5jb20iLCJ1c2VybmFtZSI6InVzdWFyaW9Vc2VyIiwicm9sZXMiOlt7Il9pZCI6IjY3YjFmOTYwMDRmYmE1Mzg2YjQ2ODZhYyIsIm5hbWUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsicXVlc3Rpb25zX3dyaXRlIiwicXVlc3Rpb25zX3JlYWQiXSwiY3JlYXRlZEF0IjoiMjAyNS0wMi0xNlQxNDo0Mjo0MC44NzFaIiwidXBkYXRlZEF0IjoiMjAyNS0wMi0xNlQxNDo0Mjo0MC44NzFaIn1dLCJpYXQiOjE3NDAxNzY4NDEsImV4cCI6MTc0MDE4NDA0MX0.NsZ2uY10WwClxxpO0QFuBmTzmXDAH1enQAV6WnIAbO0

### Listar preguntas por categoria y estado respondido
GET http://localhost:4000/api/v1/questions?category=biologia&status=answered HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjU1NDdmN2Y5M2VkNWEzYjJiY2M0MCIsImVtYWlsIjoidXNlckBnbWFpbC5jb20iLCJ1c2VybmFtZSI6InVzdWFyaW9Vc2VyIiwicm9sZXMiOlt7Il9pZCI6IjY3YjFmOTYwMDRmYmE1Mzg2YjQ2ODZhYyIsIm5hbWUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsicXVlc3Rpb25zX3dyaXRlIiwicXVlc3Rpb25zX3JlYWQiXSwiY3JlYXRlZEF0IjoiMjAyNS0wMi0xNlQxNDo0Mjo0MC44NzFaIiwidXBkYXRlZEF0IjoiMjAyNS0wMi0xNlQxNDo0Mjo0MC44NzFaIn1dLCJpYXQiOjE3NDAxNzY4NDEsImV4cCI6MTc0MDE4NDA0MX0.NsZ2uY10WwClxxpO0QFuBmTzmXDAH1enQAV6WnIAbO0

### Responder pregunta por id
PUT http://localhost:4000/api/v1/questions/67b8d5ec6c10e96c752f8987/answer HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjU1NDRmN2Y5M2VkNWEzYjJiY2MzYyIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwidXNlcm5hbWUiOiJ1c3VhcmlvQWRtaW4iLCJyb2xlcyI6W3siX2lkIjoiNjdiMWY3ZjMwNGZiYTUzODZiNDY4NmE2IiwibmFtZSI6ImFkbWluIiwicGVybWlzc2lvbnMiOlsiYWRtaW5fZ3JhbnRlZCJdLCJjcmVhdGVkQXQiOiIyMDI1LTAyLTE2VDE0OjM2OjM1LjMyMVoiLCJ1cGRhdGVkQXQiOiIyMDI1LTAyLTE2VDE0OjM2OjM1LjMyMVoifV0sImlhdCI6MTc0MDE3NDQ2NCwiZXhwIjoxNzQwMTgxNjY0fQ.FPEwkjDPbQARSJZqyjDaw3a-S_loZQ34-O8RNwB3u5s

{
  "answerUrl": "https://www.youtube.com/watch?v=cNxxnwYGsxA"
}

### Eliminar pregunta por id
DELETE http://localhost:4000/api/v1/questions/{id} HTTP/1.1
Authorization: Bearer <TU_TOKEN_DE_ADMIN>